name: 'DeployLandingZone'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env: # Set the environment variables for the whole job
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:
    - uses: actions/checkout@v4

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v3.0.0
      with:
        terraform_version: 1.1.0

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Plan'
      run: terraform plan

    - name: 'Terraform Apply'
      run: terraform apply -auto-approve

    # Use manual approval for Terraform Apply in production environments
    # - name: 'Terraform Apply'
    #   run: terraform apply -auto-approve
